sudo: false
language: ruby
cache: bundler

rvm:
- 1.9.3
- 2.0.0
- 2.1.8
- 2.2.4
- 2.3.0

gemfile:
- Gemfile.activerecord40
- Gemfile.activerecord41
- Gemfile.activerecord42
- Gemfile.activerecord50

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: Gemfile.activerecord50
    - rvm: 2.0.0
      gemfile: Gemfile.activerecord50
    - rvm: 2.1.8
      gemfile: Gemfile.activerecord50

  allow_failures:
    - gemfile: Gemfile.activerecord50

before_script:
- mysql -e 'create database database_validations;'
