sudo: false
language: ruby
cache: bundler

rvm:
- 2.1.8
- 2.2.4
- 2.3.0

gemfile:
- Gemfile.activerecord40
- Gemfile.activerecord41
- Gemfile.activerecord42
- Gemfile.activerecord50

matrix:
  exclude:
    - rvm: 2.1.8
      gemfile: Gemfile.activerecord50

before_script:
- mysql -e 'create database database_validations;'
